global using FM.Pitchside.Core.Entities;
global using FM.Pitchside.Core.Entities.Ingame;
global using FM.Pitchside.Core.Entities.Ingame.Persons;
global using FM.Pitchside.Core.VirtualMemory.Managers;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Linq;
global using System.Reflection;