<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>FMScoutFramework</AssemblyName>
    <RootNamespace>FMScoutFramework</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;WINDOWS;</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".git" />
    <None Remove=".gitignore" />
    <None Remove=".gitmodules" />
    <None Remove="kernel32.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="kernel32.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Windows.Foundation.UniversalApiContract">
      <HintPath>..\..\..\Program Files (x86)\Windows Kits\10\References\10.0.22000.0\Windows.Foundation.UniversalApiContract\14.0.0.0\Windows.Foundation.UniversalApiContract.winmd</HintPath>
    </Reference>
  </ItemGroup>

</Project>
